In [1]:
from PIL import Image

In [2]:
import os
print(os.getcwd())

/home/tobias/Code/RPM-Project-Code/Misc


In [3]:
im = Image.open("../Problems/Basic Problems B/Basic Problem B-01/1.png")

In [4]:
# print out basic instance attributes
print(im.format, im.size, im.mode)

PNG (184, 184) RGBA


In [6]:
im.show()

# Reading and writing image files

In [12]:
# convert files to JPEG
# note that JPEG does not support the Alpha (transparency) value
rgb_im = im.convert('RGB') 
rgb_im.save("example.jpg")

In [14]:
# create JPEG thumbnails
rgb_im.thumbnail((128,128))
rgb_im.save("example.jpg")

# Converting to Numpy Array and Back

In [24]:
from numpy import asarray

In [16]:
im_array = asarray(rgb_im)
print(type(im_array))

<class 'numpy.ndarray'>


In [17]:
print(im_array) # mostly white cells so you get alot of (255,255,255) values

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [18]:
# load another image
koala = Image.open("koala.jpeg")
koala.show()

In [19]:
koala_array = asarray(koala)
print(type(im_array))

<class 'numpy.ndarray'>


In [31]:
print(koala_array)

[[[ 25  26  12]
  [ 25  26  12]
  [ 25  26  12]
  ...
  [113 106  52]
  [113 106  52]
  [114 107  53]]

 [[ 25  26  12]
  [ 25  26  12]
  [ 25  26  12]
  ...
  [113 106  52]
  [113 106  52]
  [114 107  53]]

 [[ 25  26  12]
  [ 25  26  12]
  [ 25  26  12]
  ...
  [112 105  51]
  [113 106  52]
  [113 106  52]]

 ...

 [[139 118  71]
  [136 115  68]
  [130 109  62]
  ...
  [ 67  91  91]
  [ 68  89  90]
  [ 66  88  86]]

 [[150 128  81]
  [143 121  74]
  [134 111  67]
  ...
  [ 73  93  91]
  [ 69  89  87]
  [ 65  85  83]]

 [[151 127  81]
  [144 120  74]
  [135 111  67]
  ...
  [ 74  93  91]
  [ 70  89  85]
  [ 66  85  81]]]


In [32]:
# converting back from array to img
converted_koala = Image.fromarray(koala_array)

In [33]:
type(converted_koala)

PIL.Image.Image

In [34]:
converted_koala.show()